export interface Signal {
  type: string;
  description: string;
  weight: 'Primary' | 'Secondary';
  date: string;
  source_url?: string;
  fetched_at?: string;
  confidence?: number;
}

export interface BRF {
  id: string;
  name: string;
  municipality: string;
  address: string;
  district: string;
  builtYear: number;
  apartments: number;
  financialScore: number; // 0-100
  maintenanceLiability: number; // 0-100
  intentScore: number; // 0-100 (Contractor signal)
  predictedProject?: string;
  timeHorizon?: string;
  signals: Signal[];
  coordinates: { lat: number; lng: number };
  debtPerUnit: number;
  feePerKvm: number;
  feeTrajectory: 'Stable' | 'Rising 1-5%' | 'Rising 6-15%' | 'Rising 16%+' | 'Falling';
  energyClass: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
  maintenancePlanStatus: 'Aktuell' | 'Föråldrad' | 'Saknas' | 'Okänd';
  history?: HistoryItem[];
}

export interface HistoryItem {
  year: number;
  goal: string;
  outcome: string;
  status: 'Uppfyllt' | 'Delvis' | 'Ej uppfyllt' | 'Okänt';
  source: string;
  confidence: 'Hög' | 'Medel' | 'Låg';
}

export type Language = 'sv' | 'en';

export const TRANSLATIONS = {
  sv: {
    app_name: 'SIGVIK',
    tagline: 'Upphandlingsintelligens för Sveriges bostadsmarknad',
    brf_tool: 'BRF-Verktyg',
    signal_engine: 'Signalmotor (B2B)',
    find_report: 'Hitta din förenings rapportkort',
    search_placeholder: 'Sök BRF (t.ex. Slottet 1)...',
    search_results: 'Sökresultat',
    financial_health: 'Finansiell Hälsa',
    maintenance_liability: 'Underhållsskuld',
    building_info: 'Byggnadsinformation',
    built_year: 'Byggår',
    apartments: 'Antal lägenheter',
    municipality: 'Kommun',
    comparison: 'Jämförelse (Kommun)',
    recommended_actions: 'Rekommenderade åtgärder',
    weekly_intelligence: 'Veckans Intelligens',
    project_forecast: 'Projektprognos',
    intent_score: 'Intent Score',
    time_horizon: 'Tidshorisont',
    market_insight: 'Marknadsinsikt',
    live_signals: 'Live-signaler',
    version: 'Version',
    location: 'Malmö, Sverige',
    select_brf: 'Välj en förening för att se detaljerad analys',
    new_signals: 'Nya signaler denna vecka',
    region: 'Region: Malmö',
    list: 'Lista',
    map: 'Karta',
    legend: 'Teckenförklaring',
    high_intent: 'Hög Intent',
    med_intent: 'Medium Intent',
    loading: 'Laddar data...',
    privacy: 'Integritetspolicy',
    terms: 'Användarvillkor',
    gdpr: 'GDPR (LIA)',
    project_info: 'Projektinformation',
    project_description_title: 'Om SIGVIK',
    project_description_text: 'SIGVIK är en avancerad analysplattform designad för att överbrygga gapet mellan bostadsrättsföreningar (BRF) och entreprenörer. Genom att analysera publika data, årsredovisningar och fastighetssignaler identifierar vi underhållsbehov innan de blir akuta problem.',
    ui_ux_title: 'UI/UX Designfilosofi',
    ui_ux_text: 'Gränssnittet följer en "Technical Dashboard"-estetik med fokus på precision och läsbarhet. Vi använder en kombination av monospaced typsnitt för data och eleganta seriffer för redaktionellt innehåll, vilket skapar en känsla av både auktoritet och tillgänglighet.',
    generate_analysis: 'Generera Bedömning',
    analysis_title: 'Projektbedömning',
    confidence_level: 'Konfidensgrad',
    signal_pattern: 'Signalmönster',
    action_recommendation: 'Handlingsrekommendation',
    uncertainty_factors: 'Osäkerhetsfaktorer',
    signals_available: 'av 6 signaler tillgängliga',
    mandatory_disclaimer: 'Informationen på denna sida är hämtad från offentliga källor — Bolagsverkets årsredovisningar, Boverkets energideklarationer och Lantmäteriets fastighetsregister. Den tillhandahålls i informationssyfte och utgör inte finansiell, juridisk eller värderingsrådgivning. Data kan vara upp till 18 månader gammal. Begär alltid den senaste årsredovisningen direkt från föreningen eller din mäklare innan köpbeslut. SIGVIK AB ansvarar inte för beslut fattade på basis av informationen på denna sida.',
    add_missing_brf: 'Lägg till saknad BRF',
    flag_error: 'Flagga felaktig data',
    org_number: 'Organisationsnummer',
    submit: 'Skicka in',
    submission_success: 'Tack! Vi verifierar organisationsnumret mot Bolagsverket. Du får besked inom 10 arbetsdagar.',
    flag_success: 'Tack! Flaggan granskas inom 10 arbetsdagar. Fältet markeras "Data under granskning" tills felet är åtgärdat.',
    role_board: 'Styrelsemedlem',
    role_resident: 'Boende',
    role_manager: 'Förvaltare',
    role_contractor: 'Entreprenör',
    role_buyer: 'Prospektiv köpare',
    role_other: 'Annat',
    your_role: 'Din roll',
    brf_name_official: 'Föreningens namn (officiellt)',
    debt_per_unit: 'Skuld per lägenhet',
    fee_per_kvm: 'Avgift per kvm/mån',
    maintenance_plan: 'Underhållsplan',
    energy_class: 'Energiklass',
    trajectory: 'Avgiftsutveckling',
    district: 'Stadsdel',
    sample_size: 'jämfört med {count} liknande föreningar i Skåne',
    insufficient_data: 'Otillräckligt jämförelseunderlag för denna kategori',
    market_overview: 'Marknadsöversikt',
    total_brfs: 'Totalt antal BRF:er',
    avg_financial_score: 'Genomsnittlig finansiell hälsa',
    active_signals: 'Aktiva signaler',
    malmo_stats: 'Malmö Statistik',
    top_districts: 'Toppstadsdelar',
    // Phase 2 Filters
    filter_municipality: 'Kommun / Stadsdel',
    filter_apartments: 'Antal lägenheter',
    filter_built_year: 'Byggnadsår',
    filter_project_type: 'Projekttyp',
    filter_fee_trajectory: 'Avgiftsutveckling',
    filter_debt: 'Skuld per lägenhet',
    filter_energy_class: 'Energiklass',
    filter_maintenance_status: 'Underhållsplansstatus',
    // Sorting
    sort_alphabetical: 'Alfabetiskt (A–Ö)',
    sort_newest: 'Nyast data först',
    sort_debt_low: 'Lägst skuld per lägenhet',
    sort_debt_high: 'Högst skuld per lägenhet',
    sort_year_oldest: 'Byggnadsår (äldst först)',
    sort_year_newest: 'Byggnadsår (nyast först)',
    // History
    history_title: 'Föreningens historik',
    history_year: 'År',
    history_goal: 'Uttalat mål',
    history_outcome: 'Dokumenterat utfall',
    history_status: 'Status',
    history_source: 'Källa',
    history_confidence: 'Konfidens',
    history_pattern: 'Mönster att notera',
    history_questions: 'Öppna frågor för köparen',
    history_data_quality: 'Datakvalitet',
    history_disclaimer: 'Informationen baseras på offentliga Bolagsverket-handlingar. Kontrollera alltid uppgifter med mäklaren och begär senaste årsredovisningen direkt från föreningen.',
    phase2_notice: 'Den funktionen lanseras i fas 2 när vi har täckning i Stockholm och Göteborg. I prototypen visas Malmö.',
    insufficient_comparable_data: 'Otillräckligt jämförelseunderlag för denna kategori',
    data_under_review: 'Data under granskning',
    verified_registry: 'Verifierad — publika register',
    verified_community: 'Verifierad — community',
    limited_data: 'Begränsad data'
  },
  en: {
    app_name: 'SIGVIK',
    tagline: 'Procurement intelligence for Sweden\'s housing market',
    brf_tool: 'BRF Tooling',
    signal_engine: 'Signal Engine (B2B)',
    find_report: 'Find your association\'s report card',
    search_placeholder: 'Search BRF (e.g. Slottet 1)...',
    search_results: 'Search Results',
    financial_health: 'Financial Health',
    maintenance_liability: 'Maintenance Liability',
    building_info: 'Building Information',
    built_year: 'Built Year',
    apartments: 'Number of apartments',
    municipality: 'Municipality',
    comparison: 'Comparison (Municipality)',
    recommended_actions: 'Recommended Actions',
    weekly_intelligence: 'Weekly Intelligence',
    project_forecast: 'Project Forecast',
    intent_score: 'Intent Score',
    time_horizon: 'Time Horizon',
    market_insight: 'Market Insight',
    live_signals: 'Live Signals',
    version: 'Version',
    location: 'Malmö, Sweden',
    select_brf: 'Select an association to see detailed analysis',
    new_signals: 'New signals this week',
    region: 'Region: Malmö',
    list: 'List',
    map: 'Map',
    legend: 'Legend',
    high_intent: 'High Intent',
    med_intent: 'Medium Intent',
    loading: 'Loading data...',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    gdpr: 'GDPR (LIA)',
    project_info: 'Project Info',
    project_description_title: 'About SIGVIK',
    project_description_text: 'SIGVIK is an advanced analytics platform designed to bridge the gap between housing cooperatives (BRF) and contractors. By analyzing public data, annual reports, and property signals, we identify maintenance needs before they become acute problems.',
    ui_ux_title: 'UI/UX Design Philosophy',
    ui_ux_text: 'The interface follows a "Technical Dashboard" aesthetic with a focus on precision and readability. We use a combination of monospaced fonts for data and elegant serifs for editorial content, creating a sense of both authority and accessibility.',
    generate_analysis: 'Generate Assessment',
    analysis_title: 'Project Assessment',
    confidence_level: 'Confidence Level',
    signal_pattern: 'Signal Pattern',
    action_recommendation: 'Action Recommendation',
    uncertainty_factors: 'Uncertainty Factors',
    signals_available: 'of 6 signals available',
    mandatory_disclaimer: 'The information on this page is gathered from public sources — Bolagsverket annual reports, Boverket energy declarations, and Lantmäteriet property registers. It is provided for informational purposes only and does not constitute financial, legal, or valuation advice. Data may be up to 18 months old. Always request the latest annual report directly from the association or your broker before making a purchase decision. SIGVIK AB is not responsible for decisions made based on the information on this page.',
    add_missing_brf: 'Add missing BRF',
    flag_error: 'Flag data error',
    org_number: 'Organization Number',
    submit: 'Submit',
    submission_success: 'Thank you! We are verifying the organization number against Bolagsverket. You will receive an update within 10 working days.',
    flag_success: 'Thank you! The flag will be reviewed within 10 working days. The field will be marked "Data under review" until the error is corrected.',
    role_board: 'Board Member',
    role_resident: 'Resident',
    role_manager: 'Property Manager',
    role_contractor: 'Contractor',
    role_buyer: 'Prospective Buyer',
    role_other: 'Other',
    your_role: 'Your role',
    brf_name_official: 'Association name (official)',
    debt_per_unit: 'Debt per unit',
    fee_per_kvm: 'Fee per sqm/month',
    maintenance_plan: 'Maintenance Plan',
    energy_class: 'Energy Class',
    trajectory: 'Fee Trajectory',
    district: 'District',
    sample_size: 'compared to {count} similar associations in Skåne',
    insufficient_data: 'Insufficient comparable data for this category',
    market_overview: 'Market Overview',
    total_brfs: 'Total Associations',
    avg_financial_score: 'Average Financial Health',
    active_signals: 'Active Signals',
    malmo_stats: 'Malmö Statistics',
    top_districts: 'Top Districts',
    // Phase 2 Filters
    filter_municipality: 'Municipality / District',
    filter_apartments: 'Number of apartments',
    filter_built_year: 'Built Year',
    filter_project_type: 'Project Type',
    filter_fee_trajectory: 'Fee Trajectory',
    filter_debt: 'Debt per apartment',
    filter_energy_class: 'Energy Class',
    filter_maintenance_status: 'Maintenance Plan Status',
    // Sorting
    sort_alphabetical: 'Alphabetical (A–Z)',
    sort_newest: 'Newest data first',
    sort_debt_low: 'Lowest debt per apartment',
    sort_debt_high: 'Highest debt per apartment',
    sort_year_oldest: 'Built year (oldest first)',
    sort_year_newest: 'Built year (newest first)',
    // History
    history_title: 'Association History',
    history_year: 'Year',
    history_goal: 'Stated Goal',
    history_outcome: 'Documented Outcome',
    history_status: 'Status',
    history_source: 'Source',
    history_confidence: 'Confidence',
    history_pattern: 'Patterns to note',
    history_questions: 'Open questions for the buyer',
    history_data_quality: 'Data Quality',
    history_disclaimer: 'Information is based on public Bolagsverket documents. Always check information with the broker and request the latest annual report directly from the association.',
    phase2_notice: 'This function will be launched in phase 2 when we have coverage in Stockholm and Gothenburg. The prototype shows Malmö.',
    insufficient_comparable_data: 'Insufficient comparable data for this category',
    data_under_review: 'Data under review',
    verified_registry: 'Verified — public registers',
    verified_community: 'Verified — community',
    limited_data: 'Limited data'
  }
};

export const MOCK_BRFS: BRF[] = [
  // High Intent (80-95%) - 4 BRFs
  {
    id: '1',
    name: 'BRF Rönnen',
    municipality: 'Malmö',
    address: 'Rönngatan 4',
    district: 'Husie',
    builtYear: 1962,
    apartments: 48,
    financialScore: 65,
    maintenanceLiability: 82,
    intentScore: 92,
    predictedProject: 'Stambyte',
    timeHorizon: '0-6 månader',
    coordinates: { lat: 55.595, lng: 13.060 },
    debtPerUnit: 125000,
    feePerKvm: 72,
    feeTrajectory: 'Rising 16%+',
    energyClass: 'F',
    maintenancePlanStatus: 'Föråldrad',
    history: [
      { year: 2023, goal: 'Påbörja stambyte under Q4.', outcome: 'Projektet pausat pga finansieringsfrågor.', status: 'Ej uppfyllt', source: 'Årsredovisning 2023', confidence: 'Hög' },
      { year: 2022, goal: 'Utreda rörsystemets status.', outcome: 'Teknisk besiktning genomförd, läckage konstaterade.', status: 'Uppfyllt', source: 'Årsredovisning 2022', confidence: 'Hög' },
      { year: 2021, goal: 'Minska energiförbrukningen med 10%.', outcome: 'Energiförbrukningen stabil, inga åtgärder vidtagna.', status: 'Ej uppfyllt', source: 'Energideklaration', confidence: 'Hög' }
    ],
    signals: [
      { type: 'Avgiftshöjning', description: 'Planerad höjning 18%', weight: 'Primary', date: '2024-03-15', confidence: 0.95 },
      { type: 'Bygglov', description: 'Ställningsbygge ansökt', weight: 'Secondary', date: '2024-03-10', confidence: 0.90 },
      { type: 'Låneförändring', description: 'Nytt lån 5MSEK', weight: 'Primary', date: '2024-02-20', confidence: 0.98 },
      { type: 'Årsredovisning', description: 'Notering om rörläckage', weight: 'Primary', date: '2024-01-15', confidence: 0.85 },
      { type: 'Byggnadsålder', description: 'Teknisk livslängd uppnådd', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Energideklaration', description: 'Klass F - åtgärdsbehov', weight: 'Secondary', date: '2023-11-10', confidence: 0.92 }
    ]
  },
  {
    id: '2',
    name: 'BRF Pilen',
    municipality: 'Malmö',
    address: 'Pilgatan 12',
    district: 'Limhamn',
    builtYear: 1955,
    apartments: 32,
    financialScore: 45,
    maintenanceLiability: 88,
    intentScore: 88,
    predictedProject: 'Fasadrenovering',
    timeHorizon: '0-6 månader',
    coordinates: { lat: 55.585, lng: 12.930 },
    debtPerUnit: 85000,
    feePerKvm: 68,
    feeTrajectory: 'Rising 6-15%',
    energyClass: 'E',
    maintenancePlanStatus: 'Saknas',
    history: [
      { year: 2023, goal: 'Renovera fasaden mot gatan.', outcome: 'Bygglov ansökt, inväntar beslut.', status: 'Okänt', source: 'Årsredovisning 2023', confidence: 'Hög' },
      { year: 2022, goal: 'Måla om fönsterkarmar.', outcome: 'Genomfört under sommaren.', status: 'Uppfyllt', source: 'Årsredovisning 2022', confidence: 'Hög' }
    ],
    signals: [
      { type: 'Bygglov', description: 'Fasadändring beviljad', weight: 'Primary', date: '2024-03-20', confidence: 0.95 },
      { type: 'Årsredovisning', description: 'Beslut om fasadputs', weight: 'Primary', date: '2024-02-10', confidence: 0.88 },
      { type: 'Låneförändring', description: 'Refinansiering pågår', weight: 'Primary', date: '2024-02-05', confidence: 0.80 },
      { type: 'Byggnadsålder', description: 'Originalfasad från 1955', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Energideklaration', description: 'Dålig isolering noterad', weight: 'Secondary', date: '2023-12-15', confidence: 0.85 },
      { type: 'Avgiftshöjning', description: 'Höjning 10% aviserad', weight: 'Secondary', date: '2024-03-01', confidence: 0.90 }
    ]
  },
  {
    id: '3',
    name: 'BRF Triangeln',
    municipality: 'Malmö',
    address: 'Södra Förstadsgatan 22',
    district: 'Centrum',
    builtYear: 1978,
    apartments: 120,
    financialScore: 72,
    maintenanceLiability: 75,
    intentScore: 84,
    predictedProject: 'Fönsterbyte',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.595, lng: 13.000 },
    debtPerUnit: 145000,
    feePerKvm: 82,
    feeTrajectory: 'Rising 6-15%',
    energyClass: 'D',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Årsredovisning', description: 'Fönsterbyte i underhållsplan', weight: 'Primary', date: '2024-02-28', confidence: 0.92 },
      { type: 'Avgiftshöjning', description: 'Sparande till fönsterprojekt', weight: 'Primary', date: '2024-01-20', confidence: 0.85 },
      { type: 'Energideklaration', description: 'Rekommendation: 3-glasfönster', weight: 'Secondary', date: '2023-11-05', confidence: 0.90 },
      { type: 'Byggnadsålder', description: 'Originalfönster (46 år)', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Låneförändring', description: 'Låneutrymme finns', weight: 'Secondary', date: '2024-03-05', confidence: 0.75 },
      { type: 'Bygglov', description: 'Förfrågan inskickad', weight: 'Secondary', date: '2024-03-12', confidence: 0.80 }
    ]
  },
  {
    id: '4',
    name: 'BRF Turbinen',
    municipality: 'Malmö',
    address: 'Västra Varvsgatan 8',
    district: 'Västra Hamnen',
    builtYear: 2005,
    apartments: 65,
    financialScore: 85,
    maintenanceLiability: 40,
    intentScore: 82,
    predictedProject: 'Energiuppgradering',
    timeHorizon: '0-6 månader',
    coordinates: { lat: 55.615, lng: 12.975 },
    debtPerUnit: 185000,
    feePerKvm: 92,
    feeTrajectory: 'Rising 1-5%',
    energyClass: 'C',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Energideklaration', description: 'Klass C - potential för B', weight: 'Primary', date: '2024-03-10', confidence: 0.95 },
      { type: 'Årsredovisning', description: 'Investering i solceller planerad', weight: 'Primary', date: '2024-02-15', confidence: 0.90 },
      { type: 'Låneförändring', description: 'Grönt lån beviljat', weight: 'Primary', date: '2024-03-01', confidence: 0.98 },
      { type: 'Bygglov', description: 'Solcellspaneler ansökt', weight: 'Secondary', date: '2024-03-05', confidence: 0.92 },
      { type: 'Avgiftshöjning', description: 'Ingen planerad', weight: 'Secondary', date: '2024-01-01', confidence: 0.80 },
      { type: 'Byggnadsålder', description: 'Modern fastighet (19 år)', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 }
    ]
  },

  // Medium-High (60-80%) - 6 BRFs
  {
    id: '5',
    name: 'BRF Sirius',
    municipality: 'Malmö',
    address: 'Siriusgatan 15',
    district: 'Hyllie',
    builtYear: 2012,
    apartments: 92,
    financialScore: 78,
    maintenanceLiability: 30,
    intentScore: 75,
    predictedProject: 'Hissinstallation',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.565, lng: 12.975 },
    debtPerUnit: 165000,
    feePerKvm: 88,
    feeTrajectory: 'Rising 1-5%',
    energyClass: 'B',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Årsredovisning', description: 'Modernisering av hissar', weight: 'Primary', date: '2024-02-20', confidence: 0.88 },
      { type: 'Låneförändring', description: 'Lån för hissbyte upptaget', weight: 'Primary', date: '2024-03-05', confidence: 0.92 },
      { type: 'Byggnadsålder', description: '12 år - första serviceintervall', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Avgiftshöjning', description: '2% för underhållsfond', weight: 'Secondary', date: '2024-01-15', confidence: 0.85 },
      { type: 'Energideklaration', description: 'Klass B', weight: 'Secondary', date: '2023-10-10', confidence: 0.95 }
    ]
  },
  {
    id: '6',
    name: 'BRF Segevång',
    municipality: 'Malmö',
    address: 'Kronetorpsgatan 42',
    district: 'Segevång',
    builtYear: 1965,
    apartments: 180,
    financialScore: 55,
    maintenanceLiability: 70,
    intentScore: 72,
    predictedProject: 'Takunderhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.615, lng: 13.045 },
    debtPerUnit: 95000,
    feePerKvm: 62,
    feeTrajectory: 'Rising 6-15%',
    energyClass: 'E',
    maintenancePlanStatus: 'Föråldrad',
    signals: [
      { type: 'Årsredovisning', description: 'Takbesiktning utförd', weight: 'Primary', date: '2024-01-30', confidence: 0.82 },
      { type: 'Avgiftshöjning', description: 'Höjning för takfond', weight: 'Primary', date: '2024-02-15', confidence: 0.88 },
      { type: 'Byggnadsålder', description: 'Tak från 1965 (59 år)', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Energideklaration', description: 'Värmeförlust via tak', weight: 'Secondary', date: '2023-12-05', confidence: 0.75 },
      { type: 'Låneförändring', description: 'Ingen nyligen', weight: 'Secondary', date: '2024-01-01', confidence: 0.90 }
    ]
  },
  {
    id: '7',
    name: 'BRF Oxie',
    municipality: 'Malmö',
    address: 'Lärkvägen 3',
    district: 'Oxie',
    builtYear: 1982,
    apartments: 45,
    financialScore: 68,
    maintenanceLiability: 60,
    intentScore: 68,
    predictedProject: 'Stambyte',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.545, lng: 13.100 },
    debtPerUnit: 75000,
    feePerKvm: 58,
    feeTrajectory: 'Rising 1-5%',
    energyClass: 'D',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Årsredovisning', description: 'Spolning av stammar planerad', weight: 'Primary', date: '2024-02-10', confidence: 0.85 },
      { type: 'Byggnadsålder', description: '42 år - rörsystemets ålder', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Låneförändring', description: 'Mindre lån för förstudie', weight: 'Secondary', date: '2024-03-01', confidence: 0.78 },
      { type: 'Avgiftshöjning', description: '3% årlig indexering', weight: 'Secondary', date: '2024-01-01', confidence: 0.90 }
    ]
  },
  {
    id: '8',
    name: 'BRF Rosengård',
    municipality: 'Malmö',
    address: 'Adlerfelts väg 12',
    district: 'Rosengård',
    builtYear: 1970,
    apartments: 150,
    financialScore: 50,
    maintenanceLiability: 78,
    intentScore: 65,
    predictedProject: 'Fasadrenovering',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.585, lng: 13.045 },
    debtPerUnit: 110000,
    feePerKvm: 65,
    feeTrajectory: 'Rising 6-15%',
    energyClass: 'F',
    maintenancePlanStatus: 'Saknas',
    signals: [
      { type: 'Energideklaration', description: 'Klass F - fasadåtgärder', weight: 'Primary', date: '2024-02-05', confidence: 0.92 },
      { type: 'Byggnadsålder', description: 'Miljonprogram - fasadslitage', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Avgiftshöjning', description: 'Sparande påbörjat', weight: 'Secondary', date: '2024-01-20', confidence: 0.80 },
      { type: 'Årsredovisning', description: 'Diskussion om tilläggsisolering', weight: 'Secondary', date: '2024-02-28', confidence: 0.75 }
    ]
  },
  {
    id: '9',
    name: 'BRF Fosie',
    municipality: 'Malmö',
    address: 'Lindängsplan 2',
    district: 'Fosie',
    builtYear: 1974,
    apartments: 110,
    financialScore: 62,
    maintenanceLiability: 65,
    intentScore: 62,
    predictedProject: 'Fönsterbyte',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.565, lng: 13.025 },
    debtPerUnit: 105000,
    feePerKvm: 60,
    feeTrajectory: 'Rising 1-5%',
    energyClass: 'E',
    maintenancePlanStatus: 'Okänd',
    signals: [
      { type: 'Byggnadsålder', description: '50 år - originalfönster', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Årsredovisning', description: 'Fönsteröversyn planerad', weight: 'Primary', date: '2024-02-15', confidence: 0.82 },
      { type: 'Energideklaration', description: 'Drag från fönster noterad', weight: 'Secondary', date: '2023-11-20', confidence: 0.78 },
      { type: 'Avgiftshöjning', description: 'Ingen nyligen', weight: 'Secondary', date: '2024-01-01', confidence: 0.85 }
    ]
  },
  {
    id: '10',
    name: 'BRF Kirseberg',
    municipality: 'Malmö',
    address: 'Vattenverksvägen 18',
    district: 'Kirseberg',
    builtYear: 1948,
    apartments: 38,
    financialScore: 40,
    maintenanceLiability: 85,
    intentScore: 60,
    predictedProject: 'Takunderhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.610, lng: 13.035 },
    debtPerUnit: 65000,
    feePerKvm: 55,
    feeTrajectory: 'Rising 6-15%',
    energyClass: 'G',
    maintenancePlanStatus: 'Föråldrad',
    signals: [
      { type: 'Byggnadsålder', description: 'Gammal fastighet - takslitage', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Energideklaration', description: 'Klass G - akut behov', weight: 'Primary', date: '2024-03-05', confidence: 0.95 },
      { type: 'Årsredovisning', description: 'Läckage i vindsvåning', weight: 'Secondary', date: '2024-02-10', confidence: 0.88 },
      { type: 'Avgiftshöjning', description: 'Planerad 12%', weight: 'Secondary', date: '2024-03-15', confidence: 0.90 }
    ]
  },

  // Medium-Low (35-60%) - 6 BRFs (Conflicting Signals)
  {
    id: '11',
    name: 'BRF Slottet',
    municipality: 'Malmö',
    address: 'Slottsgatan 5',
    district: 'Centrum',
    builtYear: 1920,
    apartments: 25,
    financialScore: 35,
    maintenanceLiability: 90,
    intentScore: 55,
    predictedProject: 'Stambyte',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.605, lng: 13.000 },
    debtPerUnit: 55000,
    feePerKvm: 52,
    feeTrajectory: 'Rising 16%+',
    energyClass: 'G',
    maintenancePlanStatus: 'Saknas',
    signals: [
      { type: 'Byggnadsålder', description: 'Över 100 år gammal', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Låneförändring', description: 'Refinansiering nyligen klar', weight: 'Primary', date: '2024-02-20', confidence: 0.95 }, // Conflict: suggests funding done
      { type: 'Årsredovisning', description: 'Ingen projektnotering', weight: 'Secondary', date: '2024-01-15', confidence: 0.80 }
    ]
  },
  {
    id: '12',
    name: 'BRF Hamnen',
    municipality: 'Malmö',
    address: 'Dockplatsen 2',
    district: 'Västra Hamnen',
    builtYear: 2010,
    apartments: 80,
    financialScore: 80,
    maintenanceLiability: 20,
    intentScore: 48,
    predictedProject: 'Energiuppgradering',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.618, lng: 12.978 },
    debtPerUnit: 175000,
    feePerKvm: 90,
    feeTrajectory: 'Stable',
    energyClass: 'C',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Avgiftshöjning', description: 'Höjning 15% aviserad', weight: 'Primary', date: '2024-03-10', confidence: 0.95 },
      { type: 'Årsredovisning', description: 'Ingen underhållsnotering', weight: 'Primary', date: '2024-02-15', confidence: 0.85 }, // Conflict: fee up but no plan
      { type: 'Byggnadsålder', description: 'Modern (14 år)', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 }
    ]
  },
  {
    id: '13',
    name: 'BRF Parken',
    municipality: 'Malmö',
    address: 'Pildammsvägen 8',
    district: 'Centrum',
    builtYear: 1952,
    apartments: 55,
    financialScore: 58,
    maintenanceLiability: 75,
    intentScore: 45,
    predictedProject: 'Fönsterbyte',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.592, lng: 12.992 },
    debtPerUnit: 88000,
    feePerKvm: 64,
    feeTrajectory: 'Rising 1-5%',
    energyClass: 'F',
    maintenancePlanStatus: 'Föråldrad',
    signals: [
      { type: 'Energideklaration', description: 'Klass F - fönsteråtgärd', weight: 'Primary', date: '2024-02-05', confidence: 0.92 },
      { type: 'Avgiftshöjning', description: 'Stabil avgift', weight: 'Primary', date: '2024-01-01', confidence: 0.90 }, // Conflict: F class but no fee prep
      { type: 'Byggnadsålder', description: '72 år gammal', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 }
    ]
  },
  {
    id: '14',
    name: 'BRF Utsikten',
    municipality: 'Malmö',
    address: 'Hyllie Allé 22',
    district: 'Hyllie',
    builtYear: 2015,
    apartments: 110,
    financialScore: 75,
    maintenanceLiability: 15,
    intentScore: 42,
    predictedProject: 'Hissinstallation',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.562, lng: 12.982 },
    debtPerUnit: 195000,
    feePerKvm: 95,
    feeTrajectory: 'Rising 1-5%',
    energyClass: 'B',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Låneförändring', description: 'Nytt lån 2MSEK', weight: 'Primary', date: '2024-03-01', confidence: 0.98 },
      { type: 'Bygglov', description: 'Ingen aktivitet', weight: 'Primary', date: '2024-03-15', confidence: 0.90 }, // Conflict: new loan but no permit
      { type: 'Byggnadsålder', description: 'Mycket modern (9 år)', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 }
    ]
  },
  {
    id: '15',
    name: 'BRF Kvarnen',
    municipality: 'Malmö',
    address: 'Kvarnbyvägen 4',
    district: 'Husie',
    builtYear: 1988,
    apartments: 42,
    financialScore: 70,
    maintenanceLiability: 45,
    intentScore: 38,
    predictedProject: 'Takunderhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.598, lng: 13.085 },
    debtPerUnit: 82000,
    feePerKvm: 60,
    feeTrajectory: 'Stable',
    energyClass: 'C',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Årsredovisning', description: 'Hög styrelseomsättning', weight: 'Primary', date: '2024-02-10', confidence: 0.85 }, // Governance velocity spike
      { type: 'Låneförändring', description: 'Ingen aktivitet', weight: 'Primary', date: '2024-01-01', confidence: 0.90 }, // Conflict: new board but no money
      { type: 'Byggnadsålder', description: '36 år gammal', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 }
    ]
  },
  {
    id: '16',
    name: 'BRF Vågen',
    municipality: 'Malmö',
    address: 'Sundspromenaden 14',
    district: 'Västra Hamnen',
    builtYear: 2008,
    apartments: 58,
    financialScore: 82,
    maintenanceLiability: 25,
    intentScore: 35,
    predictedProject: 'Fasadrenovering',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.612, lng: 12.972 },
    debtPerUnit: 160000,
    feePerKvm: 85,
    feeTrajectory: 'Stable',
    energyClass: 'C',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Bygglov', description: 'Beviljat men återkallat', weight: 'Primary', date: '2024-03-05', confidence: 0.95 }, // Conflict: permit withdrawn
      { type: 'Årsredovisning', description: 'Projekt pausat', weight: 'Primary', date: '2024-02-20', confidence: 0.88 },
      { type: 'Byggnadsålder', description: '16 år gammal', weight: 'Secondary', date: '2024-01-01', confidence: 1.0 }
    ]
  },

  // Low Intent (15-35%) - 4 BRFs
  {
    id: '17',
    name: 'BRF Eken',
    municipality: 'Malmö',
    address: 'Ekstigen 2',
    district: 'Limhamn',
    builtYear: 2018,
    apartments: 35,
    financialScore: 90,
    maintenanceLiability: 5,
    intentScore: 25,
    predictedProject: 'Underhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.582, lng: 12.925 },
    debtPerUnit: 155000,
    feePerKvm: 82,
    feeTrajectory: 'Stable',
    energyClass: 'A',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Byggnadsålder', description: 'Nyproduktion (6 år)', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Årsredovisning', description: 'Inga planerade åtgärder', weight: 'Primary', date: '2024-02-15', confidence: 0.90 }
    ]
  },
  {
    id: '18',
    name: 'BRF Björken',
    municipality: 'Malmö',
    address: 'Björkgatan 10',
    district: 'Husie',
    builtYear: 2020,
    apartments: 45,
    financialScore: 95,
    maintenanceLiability: 2,
    intentScore: 20,
    predictedProject: 'Underhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.592, lng: 13.075 },
    debtPerUnit: 185000,
    feePerKvm: 88,
    feeTrajectory: 'Stable',
    energyClass: 'A',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Byggnadsålder', description: 'Nyproduktion (4 år)', weight: 'Primary', date: '2024-01-01', confidence: 1.0 },
      { type: 'Låneförändring', description: 'Stabila lån', weight: 'Secondary', date: '2024-01-01', confidence: 0.95 }
    ]
  },
  {
    id: '19',
    name: 'BRF Tallkotten 2',
    municipality: 'Malmö',
    address: 'Tallvägen 1',
    district: 'Oxie',
    builtYear: 2022,
    apartments: 28,
    financialScore: 98,
    maintenanceLiability: 1,
    intentScore: 18,
    predictedProject: 'Underhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.542, lng: 13.115 },
    debtPerUnit: 195000,
    feePerKvm: 92,
    feeTrajectory: 'Stable',
    energyClass: 'A',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Byggnadsålder', description: 'Nyproduktion (2 år)', weight: 'Primary', date: '2024-01-01', confidence: 1.0 }
    ]
  },
  {
    id: '20',
    name: 'BRF Solen',
    municipality: 'Malmö',
    address: 'Solgatan 4',
    district: 'Centrum',
    builtYear: 2023,
    apartments: 20,
    financialScore: 99,
    maintenanceLiability: 0,
    intentScore: 15,
    predictedProject: 'Underhåll',
    timeHorizon: '6-18 månader',
    coordinates: { lat: 55.602, lng: 13.015 },
    debtPerUnit: 205000,
    feePerKvm: 98,
    feeTrajectory: 'Stable',
    energyClass: 'A',
    maintenancePlanStatus: 'Aktuell',
    signals: [
      { type: 'Byggnadsålder', description: 'Nyproduktion (1 år)', weight: 'Primary', date: '2024-01-01', confidence: 1.0 }
    ]
  }
];
